# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', geoposition.fields.GeopositionField(max_length=42)),
                ('longitude', geoposition.fields.GeopositionField(max_length=42)),
                ('address', models.TextField()),
            ],
        ),
    ]
