# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 08:05
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_coordinate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinate',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='coordinate',
            name='longitude',
        ),
        migrations.AddField(
            model_name='coordinate',
            name='values',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True),
        ),
    ]
