# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 08:09
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20171130_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='values',
            field=geoposition.fields.GeopositionField(default=0, max_length=42),
            preserve_default=False,
        ),
    ]
