# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 03:49

from __future__ import unicode_literals

from django.db import migrations, models

import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20171130_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now()),
            preserve_default=False,
        ),
    ]
