# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressForCandidate',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='address.Address')),
            ],
            bases=('address.address',),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6)),
                ('annual_salary', models.PositiveIntegerField()),
                ('issued_date', models.DateField()),
                ('joining_date', models.DateField()),
                ('designation', models.CharField(max_length=255)),
                ('reporting_officer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContactForCandidate',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='address.Contact')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_contact', to='candidate.Candidate')),
            ],
            bases=('address.contact',),
        ),
        migrations.AddField(
            model_name='addressforcandidate',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_address', to='candidate.Candidate'),
        ),
    ]
